##
## Makefile configuration for normaliz
##

#######  customize  ######

LIBNORMALIZ_DIR = ../libnormaliz
INCLUDE_DIR = ..
MY_PROG = maxsimplex

##### end customize ######

include ../Makefile.configuration

LINKFLAGS = -L$(LIBNORMALIZ_DIR) -lnormaliz
LINKFLAGS += $(SCIPFLAGS) $(GMPFLAGS)

default: $(MY_PROG) 

%: %.cpp
	$(CXX) $(CXXFLAGS) -o $@ $< $(LINKFLAGS)

clean:
	rm -f $(MY_PROG) *.o
