##
## Makefile configuration for maxsimplex
##

#######  customize  ######

LIBNORMALIZ_DIR = ../libnormaliz
CXXFLAGS += -I ..
MY_PROG = maxsimplex

##### end customize ######

include ../Makefile.configuration

LINKFLAGS = -L$(LIBNORMALIZ_DIR) -lnormaliz
LINKFLAGS += $(SCIPFLAGS) $(COCOAFLAGS) $(FLINTFLAGS)  $(GMPFLAGS)

default: $(MY_PROG) 

%: %.cpp ../libnormaliz/libnormaliz.a
	$(CXX) $(CXXFLAGS) -o $@ $< $(LINKFLAGS)

clean:
	rm -f $(MY_PROG) *.o
