##
## Makefile configuration for normaliz
##
CXX = g++ 
CXXFLAGS += -Wall
CXXFLAGS += -pedantic -Wno-long-long
CXXFLAGS += -O3 -funroll-loops
#CXXFLAGS += -g
#CXXFLAGS += -pg

## use OpenMP?
ifeq ($(OPENMP),no)
 CXXFLAGS += -Wno-unknown-pragmas
else
 CXXFLAGS += -fopenmp
endif

NORMFLAGS = -static
GMPFLAGS = -lgmpxx -lgmp

