name: Run tests

on:
  - push
  - pull_request

jobs:

  ## Test on Mac OS X with LLVM from Homebrew for OpenMP support
  ## Build "static" Mac binary distribution and deploy to Normaliz-bindist
  ## (thus we set  NO_COVERAGE=1)
  cocoa-eantic-nauty-static:
    runs-on: macos-latest
    env:
      BUILDSYSTEM: "cocoa-eantic-nauty-static"
      CONFIGURE_FLAGS: "--enable-openmp"
      NO_COVERAGE: "1"
    steps:
      - uses: actions/checkout@v2
      - name: "Setup compiler and build tool"
        run: |
          brew reinstall llvm  automake
      - name: "Install prerequisites"
        run: |
          brew install flint
          ./install_scripts_opt/install_nmz_nauty.sh
          ./install_scripts_opt/install_nmz_arb.sh
          ./install_scripts_opt/install_nmz_e-antic.sh
          ./install_scripts_opt/install_nmz_cocoa.sh
      - name: "Build and run tests"
        run: ./.travis-build.sh # TODO/FIXME: should separate building and testing
      #- name: "Make bindist"
      #  run: ./.make-bindist.sh
      - name: "Upload coverage data to Codecov"
        uses: codecov/codecov-action@v1
