name: Run tests

on:
  - push
  - pull_request

jobs:


  eantic:
    runs-on: macos-12
    env:
      BUILDSYSTEM: "eantic"
      NO_COVERAGE: "1"
      NO_OPENMP: "1"
    steps:
      - uses: actions/checkout@v3
      - name: "Install homebrew packages"
        run: |
          brew install autoconf automake libtool gmp boost
      - name: "Install prerequisites"
        run: |
          ./install_scripts_opt/install_eantic_with_prerequisites.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Configure"
        run: .github/workflows/.github-ci-build_configure.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Build"
        run: .github/workflows/.github-ci-build_make.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Run tests"
        run: .github/workflows/.github-ci-build_check.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3

  nauty:
    runs-on: macos-latest
    env:
      BUILDSYSTEM: "nauty"
      NO_COVERAGE: "1"
    steps:
      - uses: actions/checkout@v3
      - name: "Install homebrew packages"
        run: |
          brew install autoconf automake libtool diffutiles
      - name: "Install prerequisites"
        run: |
          ./install_scripts_opt/install_nmz_nauty.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Configure"
        run: .github/workflows/.github-ci-build_configure.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Build"
        run: .github/workflows/.github-ci-build_make.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Run tests"
        run: .github/workflows/.github-ci-build_check.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3


