name: Run tests

on:
  - push
  - pull_request

jobs:


  macos_installscript-check:
    runs-on: macos-latest
    env:
      BUILDSYSTEM: "check"
      ## NORMPARA: "-x=1"
      CONFIGURE_FLAGS: "--enable-openmp"
      NO_COVERAGE: "1"
    steps:
      - uses: actions/checkout@v3
      - name: "Install homebrew packages"
        run: |
          brew install autoconf automake libtool boost llvm  libomp
      - name: "install_normaliz_with_eantic.sh"
        run: ./install_normaliz_with_eantic.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
      - name: "Run tests"
        run: |
          cd build
          ../.github/workflows/.github-ci-build_check.sh
      # - name: "Setup tmate session"
      #   uses: mxschmitt/action-tmate@v3
